### ISSUE TITLE
Latest commit - Lots of shpc sub-commands failing

### ISSUE THREAD

**Issue by marcodelapierre** [singularityhub/singularity-hpc#386]
I was trialling some commands with 0.0.25,
and kept getting this type of error:

```
$ shpc install biocontainers/samtools:v1.9-4-deb_cv1

Traceback (most recent call last):
  File "/group/pawsey0001/mdelapierre/PSS/shpc-tests/shpc-v0025/bin/shpc", line 11, in <module>
    load_entry_point('singularity-hpc', 'console_scripts', 'shpc')()
  File "/group/pawsey0001/mdelapierre/PSS/shpc-tests/shpc-v0025/shpc/client/__init__.py", line 349, in run_shpc
    main(args=args, parser=parser, extra=extra, subparser=helper)
  File "/group/pawsey0001/mdelapierre/PSS/shpc-tests/shpc-v0025/shpc/client/install.py", line 17, in main
    container_tech=args.container_tech,
  File "/group/pawsey0001/mdelapierre/PSS/shpc-tests/shpc-v0025/shpc/main/__init__.py", line 34, in get_client
    from shpc.main.modules.lmod import Client
  File "/group/pawsey0001/mdelapierre/PSS/shpc-tests/shpc-v0025/shpc/main/modules/__init__.py", line 5, in <module>
    from shpc.main.client import Client as BaseClient
  File "/group/pawsey0001/mdelapierre/PSS/shpc-tests/shpc-v0025/shpc/main/client.py", line 7, in <module>
    import shpc.main.container as container
  File "/group/pawsey0001/mdelapierre/PSS/shpc-tests/shpc-v0025/shpc/main/container/__init__.py", line 6, in <module>
    from .singularity import SingularityContainer
  File "/group/pawsey0001/mdelapierre/PSS/shpc-tests/shpc-v0025/shpc/main/container/singularity.py", line 7, in <module>
    import shpc.main.container as containers
AttributeError: module 'shpc.main' has no attribute 'container'
```

Same with `shpc show` and `shpc list` (haven't tested others)

**Comment by marcodelapierre** [comment]
NOTE: I installed 0.0.25 using `pip install -e . --prefix="$(pwd)"` as I was doing before.

**Comment by vsoch** [comment]
When you look in that container folder is there an init file?

**Comment by vsoch** [comment]
I just cloned main and created a venv and tried that command - it doesn't even work for me:

```
Installing collected packages: singularity-hpc
  Found existing installation: singularity-hpc 0.0.25
    Uninstalling singularity-hpc-0.0.25:
      Successfully uninstalled singularity-hpc-0.0.25
  Running setup.py develop for singularity-hpc
    ERROR: Command errored out with exit status 1:
     command: /tmp/singularity-hpc/env/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/singularity-hpc/setup.py'"'"'; __file__='"'"'/tmp/singularity-hpc/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps --prefix=.
         cwd: /tmp/singularity-hpc/
    Complete output (33 lines):
    running develop
    Checking .pth file support in ./lib/python3.8/site-packages
    /tmp/singularity-hpc/env/bin/python -E -c pass
    TEST FAILED: ./lib/python3.8/site-packages does NOT support .pth files
    error: bad install directory or PYTHONPATH
    
    You are attempting to install a package to a directory that is not
    on PYTHONPATH and which Python does not read ".pth" files from.  The
    installation directory you specified (via --install-dir, --prefix, or
    the distutils default setting) was:
    
        ./lib/python3.8/site-packages
    
    and your PYTHONPATH environment variable currently contains:
    
        '/tmp/singularity-hpc'
    
    Here are some of your options for correcting the problem:
    
    * You can choose a different installation directory, i.e., one that is
      on PYTHONPATH or supports .pth files
    
    * You can add the installation directory to the PYTHONPATH environment
      variable.  (It must then also be on PYTHONPATH whenever you run
      Python and want to use the package(s) you are installing.)
    
    * You can set up the installation directory to support ".pth" files by
      using one of the approaches described here:
    
      https://setuptools.readthedocs.io/en/latest/easy_install.html#custom-installation-locations
    
    
    Please make the appropriate changes for your system and try again.
    ----------------------------------------
  Rolling back uninstall of singularity-hpc
  Moving to /tmp/singularity-hpc/env/bin/shpc
   from /tmp/pip-uninstall-8qj6erqn/shpc
  Moving to /tmp/singularity-hpc/env/lib/python3.8/site-packages/singularity-hpc.egg-link
   from /tmp/pip-uninstall-h9rddgbj/singularity-hpc.egg-link
ERROR: Command errored out with exit status 1: /tmp/singularity-hpc/env/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/singularity-hpc/setup.py'"'"'; __file__='"'"'/tmp/singularity-hpc/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps --prefix=. Check the logs for full command output.
WARNING: You are using pip version 19.2.3, however version 21.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```
But this works:

```bash
pip install -e . --prefix="$(pwd)"
```
Why are you using prefix?

**Comment by vsoch** [comment]
I suspect when you do prefix it is installing in a way that it's missing that module. But I can't reproduce fully so I'm not sure!

**Comment by vsoch** [comment]
Can you try changing line 7 to:
```
import shpc.main.container import ContainerName
```
and line 104

```
parsed_name = ContainerName(module_name)
```
I remember an error like this early on when I was testing, and just changing the structure of the import fixed it.

**Comment by vsoch** [comment]
And this import would also be in podman.py. If you make those changes and it works, I can update the docker pr with it and merge that soon for a new release. The docker addition is similar enough that it should be good to go given tests are good (famous last word...)

**Comment by vsoch** [comment]
If it's an issue of a circular import (strange that it doesn't happen all the time) we can move the import down into the function.

**Comment by vsoch** [comment]
@marcodelapierre I moved the function to be in base.py and changed the imports if you want to give the add/docker branch a shot! Sorry for the bug - I didn't see it on any of my testing places or local machine.

**Comment by marcodelapierre** [comment]
works OK now with 0.0.27, thanks @vsoch !
