### ISSUE TITLE
shpc test fails with podman and docker

### ISSUE THREAD

**Issue by marcodelapierre** [singularityhub/singularity-hpc#392]
(with and without version tag)

seems like it's looking for the SIF file

```
$ shpc test biocontainers/samtools
v1.9-4-deb_cv1: Pulling from biocontainers/samtools
Digest: sha256:da61624fda230e94867c9429ca1112e1e77c24e500b52dfc84eaf2f5820b4a2a
Status: Image is up to date for biocontainers/samtools:v1.9-4-deb_cv1
docker.io/biocontainers/samtools:v1.9-4-deb_cv1
Module biocontainers/samtools:v1.9-4-deb_cv1 was created.
Traceback (most recent call last):
  File "/data/work/shpc/shpc-v0027/bin/shpc", line 33, in <module>
    sys.exit(load_entry_point('singularity-hpc', 'console_scripts', 'shpc')())
  File "/data/work/shpc/shpc-v0027/shpc/client/__init__.py", line 349, in run_shpc
    main(args=args, parser=parser, extra=extra, subparser=helper)
  File "/data/work/shpc/shpc-v0027/shpc/client/test.py", line 23, in main
    template=args.template,
  File "/data/work/shpc/shpc-v0027/shpc/main/client.py", line 148, in test
    assert os.path.exists(sif)
AssertionError

```

**Comment by vsoch** [comment]
This is an oversight on my part - the test is indeed hard coded for singularity! We probably want to keep most of test in the client, but then have it call self.container.test. I'll work on this later today.
