### ISSUE TITLE
How to enable wrapper scripts ?

### ISSUE THREAD

**Issue by muffato** [singularityhub/singularity-hpc#505]
Hello,

It seems that 
```diff
diff --git a/shpc/settings.yml b/shpc/settings.yml
index b02344346..9816ecad3 100644
--- a/shpc/settings.yml
+++ b/shpc/settings.yml
@@ -60,7 +60,7 @@ wrapper_shell: /bin/bash
 # If you want a custom wrapper script for a one-off container, define it there with the script
 # stored alongside the container.yaml.
 wrapper_scripts:
-  enabled: false
+  enabled: true
 
   # use for docker aliases (set to null to disable)
   docker: docker.sh
```
is not sufficient to get the wrapper scripts, as I get this error message:
```
$ shpc install ruby:3.0.2
singularity pull --name /lustre/scratch123/tol/teams/tolit/users/mm49/shpc/singularity-hpc/containers/ruby/3.0.2/ruby-3.0.2-sha256:15dd21ae353c5f4faebed038d9d131c47b9fd84c14be8c3cfbc750204b63f009.sif docker://ruby@sha256:15dd21ae353c5f4faebed038d9d131c47b9fd84c14be8c3cfbc750204b63f009
INFO:    Using cached SIF image
INFO:    Using cached SIF image
/lustre/scratch123/tol/teams/tolit/users/mm49/shpc/singularity-hpc/containers/ruby/3.0.2/ruby-3.0.2-sha256:15dd21ae353c5f4faebed038d9d131c47b9fd84c14be8c3cfbc750204b63f009.sif
Traceback (most recent call last):
  File "/nfs/users/nfs_m/mm49/.conda/envs/shpc/bin/shpc", line 33, in <module>
    sys.exit(load_entry_point('singularity-hpc', 'console_scripts', 'shpc')())
  File "/lustre/scratch123/tol/teams/tolit/users/mm49/shpc/singularity-hpc/shpc/client/__init__.py", line 372, in run_shpc
    main(args=args, parser=parser, extra=extra, subparser=helper)
  File "/lustre/scratch123/tol/teams/tolit/users/mm49/shpc/singularity-hpc/shpc/client/install.py", line 19, in main
    cli.install(args.install_recipe)
  File "/lustre/scratch123/tol/teams/tolit/users/mm49/shpc/singularity-hpc/shpc/main/modules/__init__.py", line 332, in install
    self.container.install(
  File "/lustre/scratch123/tol/teams/tolit/users/mm49/shpc/singularity-hpc/shpc/main/container/singularity.py", line 177, in install
    wrapper_scripts = shpc.main.wrappers.generate(
  File "/lustre/scratch123/tol/teams/tolit/users/mm49/shpc/singularity-hpc/shpc/main/wrappers/__init__.py", line 37, in generate
    generated += wrapper.generate_aliases()
  File "/lustre/scratch123/tol/teams/tolit/users/mm49/shpc/singularity-hpc/shpc/main/wrappers/base.py", line 111, in generate_aliases
    self.load_template()
  File "/lustre/scratch123/tol/teams/tolit/users/mm49/shpc/singularity-hpc/shpc/main/wrappers/base.py", line 96, in load_template
    if not os.path.exists(path):
  File "/nfs/users/nfs_m/mm49/.conda/envs/shpc/lib/python3.9/genericpath.py", line 19, in exists
    os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
```
which leaves the `modules/ruby/3.0.2/` directory empty.

To make it work, I had to make this change
```diff
diff --git a/shpc/main/wrappers/base.py b/shpc/main/wrappers/base.py
index 43a32662d..c29e45377 100644
--- a/shpc/main/wrappers/base.py
+++ b/shpc/main/wrappers/base.py
@@ -91,7 +91,7 @@ class WrapperScript:
         template_paths = [os.path.dirname(template_file), templates]
 
         # Do we have a custom template path directory?
-        if "templates" in self.settings.wrapper_scripts:
+        if self.settings.wrapper_scripts.get("templates"):
             path = self.settings.wrapper_scripts["templates"]
             if not os.path.exists(path):
                 logger.exit(
```
so that it doesn't enter the `if` (by default, `wrapper_scripts:templates` is `null`).

and then it's able to create the module and the wrapper scripts
```
modules/
└── ruby
    └── 3.0.2
        ├── 99-shpc.sh
        ├── bin
        │   ├── bundle
        │   ├── bundler
        │   ├── erb
        │   ├── gem
        │   ├── irb
        │   ├── racc
        │   ├── rake
        │   ├── rbs
        │   ├── rdoc
        │   ├── ri
        │   ├── ruby
        │   └── typeprof
        └── module.lua
```

This is on the current main branch (fc4f684be68c88b47f716352bb27fba1b425d456).

Did I misunderstand how wrapper scripts are enabled ?

Matthieu

**Comment by vsoch** [comment]
This looks like a bug - you don't have to worry about misunderstanding anything they happen sometime! Akin with your other post I'll take a look after dinner. The last PR had HUGE changes so I'm not surprised there is a bug.

**Comment by vsoch** [comment]
okay this is a pretty quick fix too - it's exactly as you suggested. The "templates" value is null by default assuming a user doesn't not want custom templates. I think it's strange that we couldn't do the direct index (as I did, because it's defined as null/None and the key is there) but if this fix does the trick that works for me. PR with box fixes coming shortly.

**Comment by vsoch** [comment]
Fix in https://github.com/singularityhub/singularity-hpc/pull/506
