### ISSUE TITLE
Error in documentation

### ISSUE THREAD

**Issue by surak** [singularityhub/singularity-hpc#572]
In https://singularity-hpc.readthedocs.io/en/latest/getting_started/use-cases.html?highlight=feature#adding-options

It says:

> By default, some of the commands will come with singularity options. For example, a container intended for gpu will have a `feature: gpu` set to `true`, and this will add the `--nv` flag given that the user or cluster settings file has that feature enabled. 

When one adds `feature` to a container.yaml file, one gets:

```python
shpc install nvcr.io/nvidia/tensorflow 
Traceback (most recent call last):
  File "/p/project/ccstao/cstao05/easybuild/juwelsbooster/software/shpc/0.0.57-GCCcore-11.2.0/bin/shpc", line 8, in <module>
    sys.exit(run_shpc())
  File "/p/project/ccstao/cstao05/easybuild/juwelsbooster/software/shpc/0.0.57-GCCcore-11.2.0/lib/python3.9/site-packages/shpc/client/__init__.py", line 454, in run_shpc
    main(args=args, parser=parser, extra=extra, subparser=helper)
  File "/p/project/ccstao/cstao05/easybuild/juwelsbooster/software/shpc/0.0.57-GCCcore-11.2.0/lib/python3.9/site-packages/shpc/client/install.py", line 30, in main
    cli.install(
  File "/p/project/ccstao/cstao05/easybuild/juwelsbooster/software/shpc/0.0.57-GCCcore-11.2.0/lib/python3.9/site-packages/shpc/main/modules/base.py", line 336, in install
    config = self._load_container(name, tag)
  File "/p/project/ccstao/cstao05/easybuild/juwelsbooster/software/shpc/0.0.57-GCCcore-11.2.0/lib/python3.9/site-packages/shpc/main/client.py", line 110, in _load_container
    config = self.load_registry_config(name)
  File "/p/project/ccstao/cstao05/easybuild/juwelsbooster/software/shpc/0.0.57-GCCcore-11.2.0/lib/python3.9/site-packages/shpc/main/client.py", line 97, in load_registry_config
    return container.ContainerConfig(package_file)
  File "/p/project/ccstao/cstao05/easybuild/juwelsbooster/software/shpc/0.0.57-GCCcore-11.2.0/lib/python3.9/site-packages/shpc/main/container/config.py", line 79, in __init__
    self.validate()
  File "/p/project/ccstao/cstao05/easybuild/juwelsbooster/software/shpc/0.0.57-GCCcore-11.2.0/lib/python3.9/site-packages/shpc/main/container/config.py", line 299, in validate
    jsonschema.validate(instance=self._config, schema=schemas.containerConfig)
  File "/p/software/juwelsbooster/stages/2022/software/Python/3.9.6-GCCcore-11.2.0/lib/python3.9/site-packages/jsonschema/validators.py", line 934, in validate
    raise error
jsonschema.exceptions.ValidationError: Additional properties are not allowed ('feature' was unexpected)
```

But `features` passes.

**Comment by vsoch** [comment]
Fixed with #573
