### ISSUE TITLE
shpc sync-registry fails

### ISSUE THREAD

**Issue by surak** [singularityhub/singularity-hpc#611]
**Describe the bug**

I literally just tried this command 

**To Reproduce**

```python
shpc sync-registry
Traceback (most recent call last):
  File "/p/software/juwelsbooster/stages/2022/software/shpc/0.1.13-GCCcore-11.2.0/bin/shpc", line 8, in <module>
    sys.exit(run_shpc())
  File "/p/software/juwelsbooster/stages/2022/software/shpc/0.1.13-GCCcore-11.2.0/lib/python3.9/site-packages/shpc/client/__init__.py", line 512, in run_shpc
    main(args=args, parser=parser, extra=extra, subparser=helper)
  File "/p/software/juwelsbooster/stages/2022/software/shpc/0.1.13-GCCcore-11.2.0/lib/python3.9/site-packages/shpc/client/sync.py", line 26, in sync_registry
    cli.registry.sync(
  File "/p/software/juwelsbooster/stages/2022/software/shpc/0.1.13-GCCcore-11.2.0/lib/python3.9/site-packages/shpc/main/registry/__init__.py", line 113, in sync
    return self._sync(
  File "/p/software/juwelsbooster/stages/2022/software/shpc/0.1.13-GCCcore-11.2.0/lib/python3.9/site-packages/shpc/main/registry/__init__.py", line 137, in _sync
    local = self.get_registry(local or self.settings.filesystem_registry)
  File "/p/software/juwelsbooster/stages/2022/software/shpc/0.1.13-GCCcore-11.2.0/lib/python3.9/site-packages/shpc/main/registry/__init__.py", line 94, in get_registry
    if Registry.matches(source):
  File "/p/software/juwelsbooster/stages/2022/software/shpc/0.1.13-GCCcore-11.2.0/lib/python3.9/site-packages/shpc/main/registry/remote.py", line 90, in matches
    return cls.provider_name in source and source.startswith("http")
TypeError: argument of type 'NoneType' is not iterable
```

**Version of Singularity and Singularity Registry HPC Client**
apptainer version 1.0.3-1.el8
shpc 0.1.13

**Comment by vsoch** [comment]
@muffato I think you did refactoring here last - could you take a look? We shouldn't be handing a None value to the source so something is up. If not I'll look this evening.

**Comment by vsoch** [comment]
okay I had a minute! The bug here is that you are trying to sync without a filesystem registry, which we didn't anticipate it seems. https://github.com/singularityhub/singularity-hpc/pull/612
